name: spo_env
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.8
  - attr=2.5.1
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.5.7
  - certifi=2023.5.7
  - cycler=0.11.0
  - dbus=1.13.6
  - expat=2.5.0
  - fftw=3.3.10
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.38.0
  - freetype=2.12.1
  - gettext=0.21.1
  - glib=2.76.3
  - glib-tools=2.76.3
  - gst-plugins-base=1.21.3
  - gstreamer=1.21.3
  - gstreamer-orc=0.4.33
  - icu=70.1
  - jack=1.9.22
  - jpeg=9e
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.14
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.67
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcups=2.3.3
  - libdb=6.2.32
  - libdeflate=1.14
  - libedit=3.1.20191231
  - libevent=2.1.10
  - libexpat=2.5.0
  - libffi=3.4.2
  - libflac=1.4.2
  - libgcc-ng=12.2.0
  - libgcrypt=1.10.1
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libglib=2.76.3
  - libgomp=12.2.0
  - libgpg-error=1.46
  - libiconv=1.17
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libllvm15=15.0.7
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=15.3
  - libsndfile=1.2.0
  - libsqlite=3.42.0
  - libstdcxx-ng=12.2.0
  - libsystemd0=253
  - libtiff=4.4.0
  - libtool=2.4.7
  - libudev1=253
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libwebp-base=1.3.0
  - libxcb=1.13
  - libxkbcommon=1.5.0
  - libxml2=2.10.3
  - libzlib=1.2.13
  - llvmlite=0.38.1
  - lz4-c=1.9.4
  - matplotlib=3.5.2
  - matplotlib-base=3.5.2
  - mpg123=1.31.3
  - mpi=1.0
  - mpi4py=3.1.3
  - mpich=4.1.1
  - munkres=1.1.4
  - mysql-common=8.0.32
  - mysql-libs=8.0.32
  - ncurses=6.3
  - nspr=4.35
  - nss=3.89
  - numba=0.55.2
  - numpy=1.21.6
  - openjpeg=2.5.0
  - openssl=3.1.0
  - packaging=23.1
  - pathlib2=2.3.7.post1
  - pcre2=10.40
  - pillow=9.2.0
  - pip=23.1.2
  - ply=3.11
  - pthread-stubs=0.4
  - pulseaudio=16.1
  - pulseaudio-client=16.1
  - pulseaudio-daemon=16.1
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - python=3.7.12
  - python-dateutil=2.8.2
  - python_abi=3.7
  - qt-main=5.15.6
  - readline=8.2
  - setuptools=67.7.2
  - sip=6.7.2
  - six=1.16.0
  - sqlite=3.42.0
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.2
  - typing-extensions=4.6.1
  - typing_extensions=4.6.1
  - unicodedata2=14.0.0
  - wheel=0.40.0
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.38
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - about-time==4.2.1
    - alive-progress==3.1.2
    - autograd==1.5
    - cma==3.2.2
    - deprecated==1.2.13
    - dill==0.3.6
    - future==0.18.3
    - grapheme==0.6.0
    - lhsmdu==1.1
    - pymoo==0.6.0.1
    - scipy==1.7.3
    - wrapt==1.15.0
